# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isotopo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('formula', models.CharField(max_length=50)),
            ],
        ),
    ]
